package services;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

import services.common.AppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 27 16:28:42 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    public void setSessionValues(String orgId, String userId, String respId,
                                      String respAppl) {
           
         System.out.println("User Id--> " + userId);
         System.out.println("Reps Id --> " + respId);
         System.out.println("Org Id --> " + orgId);
         if (userId != null) {
             //String flag = getFlagValue(userId, respId);
             
             FacesContext fctx = FacesContext.getCurrentInstance();
             ExternalContext ectx = fctx.getExternalContext();
             HttpSession userSession = (HttpSession)ectx.getSession(false);
             //userSession.setAttribute("Flag", flag);
             userSession.setAttribute("userId", userId);
             userSession.setAttribute("respId", respId);
             userSession.setAttribute("orgId", orgId);
             userSession.setAttribute("respAppl", respAppl);
             System.out.println(userId);
         }
     }


    /**
     * Container's getter for SummaryVO1.
     * @return SummaryVO1
     */
    public ViewObjectImpl getSummaryVO1() {
        return (ViewObjectImpl)findViewObject("SummaryVO1");
    }

    /**
     * Container's getter for SearchVO1.
     * @return SearchVO1
     */
    public ViewObjectImpl getSearchVO1() {
        return (ViewObjectImpl)findViewObject("SearchVO1");
    }

    /**
     * Container's getter for Summary2VO1.
     * @return Summary2VO1
     */
    public ViewObjectImpl getSummary2VO1() {
        return (ViewObjectImpl)findViewObject("Summary2VO1");
    }
}
